const db = require('./database');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');

const hash = (pw) => bcrypt.hashSync(pw, 10);

// ─── SUPERADMIN ─────────────────────────────────────────────
db.prepare(`INSERT OR IGNORE INTO superadmins (username, email, password, full_name) VALUES (?, ?, ?, ?)`)
  .run('superadmin', 'superadmin@erp.cz', hash('super123'), 'Super Admin');

// ─── DEFAULT TENANT (RFI) ───────────────────────────────────
const existingTenant = db.prepare("SELECT id FROM tenants WHERE slug = 'rfi'").get();
let tenantId;
if (!existingTenant) {
  const inviteCode = crypto.randomBytes(6).toString('hex');
  const r = db.prepare("INSERT INTO tenants (name, slug, invite_code) VALUES ('Rainbow Family Investment s.r.o.', 'rfi', ?)").run(inviteCode);
  tenantId = r.lastInsertRowid;
} else {
  tenantId = existingTenant.id;
  // Ensure invite_code exists
  const t = db.prepare("SELECT invite_code FROM tenants WHERE id = ?").get(tenantId);
  if (!t.invite_code) {
    const inviteCode = crypto.randomBytes(6).toString('hex');
    db.prepare("UPDATE tenants SET invite_code = ? WHERE id = ?").run(inviteCode, tenantId);
  }
}

// ─── USERS (globally unique usernames) ──────────────────────
const insertUser = db.prepare(`INSERT OR IGNORE INTO users (tenant_id, username, email, password, full_name, first_name, last_name, role) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`);
insertUser.run(tenantId, 'admin', 'admin@firma.cz', hash('admin123'), 'Jan Novák', 'Jan', 'Novák', 'admin');
insertUser.run(tenantId, 'ucetni', 'ucetni@firma.cz', hash('ucetni123'), 'Marie Dvořáková', 'Marie', 'Dvořáková', 'accountant');
insertUser.run(tenantId, 'manager', 'manager@firma.cz', hash('manager123'), 'Petr Svoboda', 'Petr', 'Svoboda', 'manager');
insertUser.run(tenantId, 'viewer', 'viewer@firma.cz', hash('viewer123'), 'Eva Černá', 'Eva', 'Černá', 'viewer');

// ─── CURRENCIES (global) ────────────────────────────────────
const insertCurrency = db.prepare(`INSERT OR IGNORE INTO currencies (code, name, symbol, rate_to_czk) VALUES (?, ?, ?, ?)`);
insertCurrency.run('CZK', 'Česká koruna', 'Kč', 1.0);
insertCurrency.run('EUR', 'Euro', '€', 25.20);
insertCurrency.run('USD', 'US Dollar', '$', 23.50);
insertCurrency.run('GBP', 'British Pound', '£', 29.80);
insertCurrency.run('PLN', 'Polský zlotý', 'zł', 5.85);

// ─── CLIENTS (tenant-scoped) ────────────────────────────────
const insertClient = db.prepare(`INSERT OR IGNORE INTO clients (tenant_id, name, ico, dic, email, phone, address, city, zip, country) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);
const clients = [
  ['TechSoft s.r.o.', '12345678', 'CZ12345678', 'info@techsoft.cz', '+420 111 222 333', 'Vinohradská 10', 'Praha', '12000', 'CZ'],
  ['DataPro a.s.', '87654321', 'CZ87654321', 'kontakt@datapro.cz', '+420 444 555 666', 'Masarykova 5', 'Brno', '60200', 'CZ'],
  ['EuroTrade GmbH', 'DE123456', 'DE123456789', 'office@eurotrade.de', '+49 30 12345', 'Berliner Str. 42', 'Berlin', '10115', 'DE'],
  ['WebDesign Studio', '11223344', 'CZ11223344', 'studio@webdesign.cz', '+420 777 888 999', 'Dlouhá 15', 'Ostrava', '70200', 'CZ'],
  ['Nordic Solutions ApS', 'DK556677', 'DK55667788', 'hello@nordic.dk', '+45 12 34 56 78', 'Nørregade 8', 'København', '1165', 'DK'],
];
clients.forEach(c => insertClient.run(tenantId, ...c));

// ─── INVOICES (tenant-scoped) ───────────────────────────────
const adminUser = db.prepare("SELECT id FROM users WHERE username = 'admin' AND tenant_id = ?").get(tenantId);
const ucetniUser = db.prepare("SELECT id FROM users WHERE username = 'ucetni' AND tenant_id = ?").get(tenantId);
const adminId = adminUser?.id || 1;
const ucetniId = ucetniUser?.id || 2;

const insertInvoice = db.prepare(`
  INSERT OR IGNORE INTO invoices (tenant_id, invoice_number, type, client_id, issue_date, due_date, paid_date, status, currency, subtotal, tax_rate, tax_amount, total, total_czk, note, created_by)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);
const insertItem = db.prepare(`INSERT INTO invoice_items (invoice_id, description, quantity, unit, unit_price, total) VALUES (?, ?, ?, ?, ?, ?)`);

const getClientId = (name) => {
  const c = db.prepare("SELECT id FROM clients WHERE name = ? AND tenant_id = ?").get(name, tenantId);
  return c?.id;
};

const invoices = [
  ['FV-2026-001', 'issued', 'TechSoft s.r.o.', '2026-01-15', '2026-02-14', '2026-02-10', 'paid', 'CZK', 50000, 21, 10500, 60500, 60500, 'Vývoj webové aplikace', adminId],
  ['FV-2026-002', 'issued', 'DataPro a.s.', '2026-01-20', '2026-02-19', null, 'overdue', 'CZK', 35000, 21, 7350, 42350, 42350, 'Konzultace a analýza', adminId],
  ['FV-2026-003', 'issued', 'EuroTrade GmbH', '2026-02-01', '2026-03-03', '2026-02-28', 'paid', 'EUR', 2000, 21, 420, 2420, 60984, 'Software development', adminId],
  ['FV-2026-004', 'issued', 'WebDesign Studio', '2026-02-10', '2026-03-12', null, 'sent', 'CZK', 18000, 21, 3780, 21780, 21780, 'Grafický návrh', ucetniId],
  ['FV-2026-005', 'issued', 'TechSoft s.r.o.', '2026-02-15', '2026-03-17', null, 'draft', 'CZK', 75000, 21, 15750, 90750, 90750, 'Údržba systému Q1', adminId],
  ['FV-2026-006', 'issued', 'Nordic Solutions ApS', '2026-03-01', '2026-03-31', null, 'sent', 'EUR', 5000, 0, 0, 5000, 126000, 'Consulting services', adminId],
  ['FP-2026-001', 'received', 'DataPro a.s.', '2026-01-05', '2026-01-19', '2026-01-18', 'paid', 'CZK', 12000, 21, 2520, 14520, 14520, 'Licence software', adminId],
  ['FP-2026-002', 'received', 'EuroTrade GmbH', '2026-02-01', '2026-02-28', null, 'overdue', 'EUR', 800, 19, 152, 952, 23990, 'Cloud hosting', adminId],
  ['FV-2026-007', 'issued', 'DataPro a.s.', '2026-03-05', '2026-04-04', null, 'draft', 'CZK', 45000, 21, 9450, 54450, 54450, 'API integrace', ucetniId],
  ['FV-2026-008', 'issued', 'WebDesign Studio', '2026-03-10', '2026-04-09', null, 'sent', 'USD', 3000, 21, 630, 3630, 85305, 'Mobile app development', adminId],
];
invoices.forEach(inv => {
  const clientId = getClientId(inv[2]);
  const info = insertInvoice.run(tenantId, inv[0], inv[1], clientId, inv[3], inv[4], inv[5], inv[6], inv[7], inv[8], inv[9], inv[10], inv[11], inv[12], inv[13], inv[14]);
  if (info.changes > 0) {
    const invId = info.lastInsertRowid;
    insertItem.run(invId, inv[13] || 'Služba', 1, 'ks', inv[8], inv[8]);
  }
});

// ─── EVIDENCE (tenant-scoped) ───────────────────────────────
const insertEvidence = db.prepare(`INSERT OR IGNORE INTO evidence (tenant_id, type, title, description, amount, currency, date, category, invoice_id, created_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);
const evidenceData = [
  ['income', 'Platba za FV-2026-001', 'Přijatá platba za vývoj', 60500, 'CZK', '2026-02-10', 'Služby', 1, adminId],
  ['income', 'Platba za FV-2026-003', 'Payment received', 2420, 'EUR', '2026-02-28', 'Služby', 3, adminId],
  ['expense', 'Licence software', 'Roční licence', 14520, 'CZK', '2026-01-18', 'Software', 7, adminId],
  ['expense', 'Kancelářské potřeby', 'Papír, tonery', 3500, 'CZK', '2026-01-25', 'Kancelář', null, ucetniId],
  ['expense', 'Hosting serveru', 'Měsíční hosting', 2500, 'CZK', '2026-02-01', 'IT', null, adminId],
  ['asset', 'MacBook Pro', 'Nový notebook pro vývojáře', 65000, 'CZK', '2026-01-10', 'Hardware', null, adminId],
  ['document', 'Smlouva TechSoft', 'Rámcová smlouva 2026', null, 'CZK', '2026-01-01', 'Smlouvy', null, adminId],
  ['income', 'Platba za FP-2026-001', 'Uhrazená faktura', 14520, 'CZK', '2026-01-18', 'Software', 7, adminId],
  ['expense', 'Cestovné Brno', 'Služební cesta', 1850, 'CZK', '2026-02-15', 'Cestovné', null, ucetniId],
  ['expense', 'Školení React', 'Online kurz', 8900, 'CZK', '2026-03-01', 'Vzdělávání', null, adminId],
];
evidenceData.forEach(e => insertEvidence.run(tenantId, ...e));

// ─── COMPANY (tenant-scoped) ────────────────────────────────
// Rainbow Family Investment brand logo (Prismatic Spectrum, white background)
const brandLogoSvg = '<svg xmlns="http://www.w3.org/2000/svg" width="300" height="80" viewBox="0 0 300 80"><rect width="300" height="80" fill="white"/><defs><linearGradient id="sp" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#1E2A3A"/><stop offset="20%" stop-color="#2D5A1E"/><stop offset="40%" stop-color="#7C8C6E"/><stop offset="60%" stop-color="#C4A265"/><stop offset="80%" stop-color="#C47D5A"/><stop offset="100%" stop-color="#8B5A6B"/></linearGradient></defs><rect x="12" y="12" width="4" height="56" rx="2" fill="url(#sp)"/><text x="26" y="44" font-family="Georgia,serif" font-size="30" font-weight="700" fill="#1E2A3A">Rainbow Family</text><text x="27" y="62" font-family="Arial,Helvetica,sans-serif" font-size="11" font-weight="500" fill="#1E2A3A" letter-spacing="4" opacity="0.45">INVESTMENT</text></svg>';
const brandLogo = 'data:image/svg+xml;base64,' + Buffer.from(brandLogoSvg).toString('base64');

const existingCompany = db.prepare('SELECT id FROM company WHERE tenant_id = ?').get(tenantId);
if (!existingCompany) {
  db.prepare(`INSERT INTO company (tenant_id, name, ico, dic, bank_account, bank_code, iban, invoice_prefix, invoice_counter, logo) VALUES (?, 'Rainbow Family Investment s.r.o.', '23486899', 'CZ23486899', '1234567890', '0100', 'CZ6501000000001234567890', 'FV', 11, ?)`).run(tenantId, brandLogo);
} else {
  // Ensure bank details and logo exist for existing records
  const comp = db.prepare('SELECT bank_account, logo FROM company WHERE tenant_id = ?').get(tenantId);
  if (!comp.bank_account) {
    db.prepare("UPDATE company SET bank_account='1234567890', bank_code='0100', iban='CZ6501000000001234567890' WHERE tenant_id=?").run(tenantId);
  }
  // Update logo to brand version
  db.prepare("UPDATE company SET logo = ? WHERE tenant_id = ?").run(brandLogo, tenantId);
}

// ─── CHATBOT KNOWLEDGE BASE (comprehensive FAQ) ─────────────
const insertKnowledge = db.prepare(`INSERT OR IGNORE INTO chatbot_knowledge (tenant_id, keywords, question_cs, question_en, answer_cs, answer_en, link, category, priority) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`);
const knowledge = [
  // ═══════════════════════════════════════
  // NAVIGATION — where to find things
  // ═══════════════════════════════════════
  ['dashboard,přehled,hlavní stránka,home,domů,úvod,nástěnka', 'Kde najdu přehled?', 'Where is the dashboard?', 'Dashboard najdete na hlavní stránce po přihlášení. Zobrazuje finanční přehled — graf příjmů a výdajů, stav faktur, top klienty a stárnutí pohledávek.', 'The dashboard is on the main page after login. It shows financial overview — revenue/expense charts, invoice status, top clients and aging report.', '/', 'navigation', 10],
  ['faktura,faktury,invoice,invoices,vystavit,nová faktura,přehled faktur,kde najdu faktury,kde jsou faktury', 'Kde najdu faktury?', 'Where are invoices?', 'Faktury najdete v sekci Finance → Faktury. Zde vidíte přehled všech vydaných i přijatých faktur s možností filtrování a vyhledávání.', 'Invoices are in the Finance → Invoices section. Here you see all issued and received invoices with filtering and search.', '/invoices', 'navigation', 10],
  ['klient,klienti,clients,zákazník,odběratel,kontakt,dodavatel', 'Kde spravuji klienty?', 'Where do I manage clients?', 'Klienty najdete v sekci Finance → Klienti. Zde můžete přidávat, upravovat a mazat klienty, vidět jejich faktury a kontaktní údaje.', 'Clients are in Finance → Clients. Here you can add, edit and delete clients, see their invoices and contact info.', '/clients', 'navigation', 10],
  ['evidence,doklady,náklady,příjmy,výdaje,přijatý doklad', 'Co je evidence a kde ji najdu?', 'What is evidence?', 'Evidence slouží k záznamu přijatých dokladů, příjmů, výdajů, majetku a dokumentů. Najdete ji v sekci Finance → Evidence. Můžete nahrávat soubory a kategorizovat záznamy.', 'Evidence is for recording received documents, income, expenses, assets and documents. Find it in Finance → Evidence.', '/evidence', 'navigation', 8],
  ['opakované,recurring,automatické,pravidelné,šablona faktury', 'Kde nastavím opakované faktury?', 'Where are recurring invoices?', 'V sekci Finance → Opakované. Vytvořte šablonu faktury s intervalem (týdně/měsíčně/čtvrtletně/ročně) a systém je bude automaticky generovat.', 'In Finance → Recurring. Create an invoice template with interval (weekly/monthly/quarterly/yearly) and the system generates them automatically.', '/recurring', 'navigation', 8],
  ['banka,bankovní,účet,transakce,párování,výpis', 'Kde najdu bankovní transakce?', 'Where are bank transactions?', 'Bankovní transakce najdete v sekci Účetnictví → Banka. Můžete importovat bankovní výpisy, párovat transakce s fakturami a spravovat bankovní účty.', 'Bank transactions are in Accounting → Bank. You can import bank statements, match transactions with invoices and manage bank accounts.', '/bank', 'navigation', 8],
  ['účetnictví,accounting,účtová osnova,předkontace,deník,hlavní kniha,účetní', 'Kde je účetnictví?', 'Where is accounting?', 'Účetnictví najdete v sekci Účetnictví → Účetnictví. Obsahuje účtovou osnovu, účetní deník (žurnál) a hlavní knihu (ledger). Můžete vytvářet účetní záznamy, zaúčtovat je a generovat výkazy.', 'Accounting is in the Accounting section. It contains the chart of accounts, journal and general ledger.', '/accounting', 'navigation', 8],
  ['dph,daň,vat,přiznání,kontrolní hlášení,sazba', 'Kde najdu DPH?', 'Where is VAT?', 'Přiznání k DPH najdete v Účetnictví → DPH. Generujte měsíční/čtvrtletní přehledy DPH, kontrolujte vstupy a výstupy.', 'VAT reports are in Accounting → VAT. Generate monthly/quarterly VAT overviews, check inputs and outputs.', '/vat', 'navigation', 8],
  ['měna,měny,kurz,currencies,exchange,směnný,cizí měna', 'Kde nastavím měny?', 'Where to set currencies?', 'Správu měn najdete v Účetnictví → Měny. Kurzy se automaticky aktualizují z ČNB. Podporujeme CZK, EUR, USD, GBP a PLN.', 'Currency management is in Accounting → Currencies. Rates auto-update from CNB. We support CZK, EUR, USD, GBP and PLN.', '/currencies', 'navigation', 7],
  ['společnost,firma,nastavení společnosti,company,settings,nastavení,kde nastavím firmu,kde nastavim firmu,nastavit firmu', 'Kde nastavím firmu?', 'Where to set company?', 'Nastavení společnosti najdete v Správa → Společnost. Upravte název, IČO, DIČ, adresu, logo, bankovní spojení, číselnou řadu faktur a vzhled.', 'Company settings are in Admin → Company. Edit name, ID, VAT ID, address, logo, bank details, invoice numbering and layout.', '/company', 'navigation', 12],
  ['uživatel,uživatelé,users,role,oprávnění,přidat uživatele,správa uživatelů', 'Kde spravuji uživatele?', 'Where to manage users?', 'Správu uživatelů najdete v Správa → Uživatelé (pouze administrátor). Přidávejte/odebírejte uživatele, měňte role (admin, účetní, manažer, náhled) a spravujte skupiny.', 'User management is in Admin → Users (admin only). Add/remove users, change roles (admin, accountant, manager, viewer) and manage groups.', '/users', 'navigation', 9],
  ['profil,heslo,podpis,profile,password,signature,osobní', 'Kde změním profil?', 'Where to change profile?', 'Váš profil najdete kliknutím na své jméno v postranním panelu nebo přes Můj profil. Změňte heslo, upravte jméno a nastavte elektronický podpis.', 'Your profile is accessible by clicking your name in the sidebar or via My Profile. Change password, edit name and set a signature.', '/profile', 'navigation', 7],

  // ═══════════════════════════════════════
  // INVOICE OPERATIONS — creating, managing
  // ═══════════════════════════════════════
  ['vytvořit fakturu,nová faktura,vystavit fakturu,create invoice,jak vytvořím fakturu,jak vytvorim fakturu,jak udělám fakturu', 'Jak vytvořím fakturu?', 'How to create an invoice?', 'Přejděte do Faktury → klikněte "+ Nová faktura". Vyberte klienta (nebo ho rovnou vytvořte), přidejte položky s popisem, množstvím a cenou, nastavte datum splatnosti a uložte. Systém automaticky přiřadí číslo faktury.', 'Go to Invoices → click "+ New invoice". Select a client, add items with description, quantity and price, set due date and save. The system auto-assigns an invoice number.', '/invoices/new', 'feature', 10],
  ['upravit fakturu,editovat,změnit fakturu,edit invoice', 'Jak upravím existující fakturu?', 'How to edit an invoice?', 'V seznamu faktur klikněte na fakturu, pak v detailu klikněte na tlačítko "Upravit". Můžete měnit položky, klienta, datum a další údaje. Upozornění: zaplacené faktury nelze editovat.', 'In the invoice list click on the invoice, then click "Edit" in the detail. You can change items, client, dates etc. Note: paid invoices cannot be edited.', '/invoices', 'feature', 8],
  ['smazat fakturu,odstranit,delete invoice', 'Jak smažu fakturu?', 'How to delete an invoice?', 'V detailu faktury najdete tlačítko "Smazat" (červené). Smazat lze pouze koncepty a stornované faktury. Odeslanou nebo zaplacenou fakturu je třeba nejprve stornovat.', 'In the invoice detail find the "Delete" button (red). Only drafts and cancelled invoices can be deleted. Sent or paid invoices must be cancelled first.', '/invoices', 'feature', 7],
  ['duplikovat fakturu,kopírovat,duplicate,kopie', 'Jak zkopíruji fakturu?', 'How to duplicate an invoice?', 'V detailu faktury klikněte na "Duplikovat". Vytvoří se nový koncept se stejnými položkami, klientem a částkami. Můžete pak upravit datum a detaily.', 'In the invoice detail click "Duplicate". A new draft is created with the same items, client and amounts. You can then modify dates and details.', '/invoices', 'feature', 7],
  ['dobropis,credit note,opravný doklad,storno', 'Jak vytvořím dobropis?', 'How to create a credit note?', 'V detailu faktury klikněte na "Vystavit dobropis". Systém vytvoří opravný daňový doklad se zápornými částkami odkazující na původní fakturu.', 'In the invoice detail click "Create credit note". The system creates a corrective tax document with negative amounts referencing the original invoice.', '/invoices', 'feature', 8],
  ['proforma,zálohová faktura,proforma invoice,záloha', 'Co je proforma faktura?', 'What is a proforma invoice?', 'Proforma faktura je nezávazný doklad pro zálohu. Při vytváření faktury zvolte typ "Proforma". Po zaplacení ji můžete převést na řádnou fakturu tlačítkem "Převést na fakturu".', 'A proforma invoice is a preliminary document for advance payment. When creating, select type "Proforma". After payment, convert it to a regular invoice with "Convert to invoice".', '/invoices/new', 'feature', 8],
  ['stav faktury,status,označit jako,změnit stav', 'Jak změním stav faktury?', 'How to change invoice status?', 'V detailu faktury najdete tlačítka pro změnu stavu: Odeslat, Zaplatit, Stornovat. Stav "Po splatnosti" se nastavuje automaticky. Můžete také hromadně měnit stav výběrem více faktur.', 'In the invoice detail find buttons to change status: Send, Pay, Cancel. "Overdue" status is set automatically. You can also bulk-change status by selecting multiple invoices.', '/invoices', 'feature', 7],
  ['pdf,stáhnout pdf,export pdf,tisk,tisknout,print', 'Jak stáhnu PDF?', 'How to download PDF?', 'V detailu faktury klikněte na "Stáhnout PDF". PDF se vygeneruje v nastaveném layoutu (klasický, minimalistický, korporátní, elegantní, kompaktní) s logem vaší společnosti a QR kódem pro platbu.', 'In the invoice detail click "Download PDF". PDF is generated in your chosen layout (classic, minimal, corporate, elegant, compact) with your company logo and payment QR code.', '/invoices', 'feature', 9],
  ['email,odeslat emailem,send email,faktura emailem', 'Jak pošlu fakturu emailem?', 'How to send invoice by email?', 'V detailu faktury klikněte na "Odeslat emailem". Vyplňte email příjemce, předmět a zprávu. Faktura se odešle jako PDF příloha a stav se automaticky změní na "Odeslaná".', 'In the invoice detail click "Send by email". Fill in recipient email, subject and message. The invoice is sent as a PDF attachment and status changes to "Sent".', '/invoices', 'feature', 8],
  ['upomínka,reminder,připomínka,urgence', 'Jak pošlu upomínku?', 'How to send a payment reminder?', 'V detailu faktury po splatnosti klikněte na "Odeslat upomínku". Klientovi se odešle email s připomínkou nezaplacené faktury.', 'In the overdue invoice detail click "Send reminder". The client receives an email reminding about the unpaid invoice.', '/invoices', 'feature', 7],
  ['variabilní symbol,variable symbol,vs', 'Co je variabilní symbol?', 'What is a variable symbol?', 'Variabilní symbol je identifikátor platby, obvykle číslo faktury. Banka ho používá pro párování plateb s fakturami. Nastavuje se automaticky při vytvoření faktury.', 'A variable symbol is a payment identifier, usually the invoice number. Banks use it to match payments with invoices. It is set automatically when creating an invoice.', '/invoices', 'terminology', 7],
  ['číslo faktury,invoice number,číselná řada,pořadí', 'Jak funguje číslování faktur?', 'How does invoice numbering work?', 'Číselnou řadu nastavíte v Správa → Společnost. Zvolte formát (prefix-rok-číslo, apod.), oddělovač, počet číslic a prefix. Čísla se přiřazují automaticky. Příklad: FV-2026-001.', 'Invoice numbering is set in Admin → Company. Choose format (prefix-year-number, etc.), separator, digits and prefix. Numbers are assigned automatically. Example: FV-2026-001.', '/company', 'feature', 7],
  ['hromadně,bulk,hromadná operace,vybrat více', 'Jak hromadně měním stav faktur?', 'How to bulk change invoice status?', 'V seznamu faktur zaškrtněte checkboxy u více faktur najednou a použijte tlačítko pro hromadnou změnu stavu (např. označit jako odeslané nebo zaplacené).', 'In the invoice list check the checkboxes on multiple invoices and use the bulk status change button (e.g. mark as sent or paid).', '/invoices', 'feature', 6],
  ['isdoc,xml,elektronická faktura,e-faktura', 'Co je ISDOC?', 'What is ISDOC?', 'ISDOC je český standard pro elektronickou fakturaci ve formátu XML. V detailu faktury můžete stáhnout ISDOC soubor pro elektronické zpracování.', 'ISDOC is a Czech standard for electronic invoicing in XML format. In the invoice detail you can download an ISDOC file for electronic processing.', '/invoices', 'terminology', 6],

  // ═══════════════════════════════════════
  // PAYMENTS & BANKING
  // ═══════════════════════════════════════
  ['zaplatit,platba,payment,uhradit,zaplacení,přijmout platbu', 'Jak zaznamenám platbu?', 'How to record a payment?', 'V detailu faktury klikněte na "Zaplatit" nebo "Přidat platbu". Zadejte částku, datum a poznámku. Systém podporuje i částečné platby — faktura se označí jako zaplacená až po uhrazení celé částky.', 'In the invoice detail click "Pay" or "Add payment". Enter amount, date and note. The system supports partial payments — invoice is marked as paid only after full amount.', '/invoices', 'feature', 9],
  ['částečná platba,partial payment,splátka,záloha', 'Jak fungují částečné platby?', 'How do partial payments work?', 'Každá faktura může mít více plateb. V detailu faktury najdete přehled plateb s částkami a daty. Stav se změní na "Zaplacená" až po úhradě celé částky.', 'Each invoice can have multiple payments. In the invoice detail you can see payment overview with amounts and dates. Status changes to "Paid" only after full payment.', '/invoices', 'feature', 7],
  ['import bankovní výpis,importovat transakce,bank import,csv', 'Jak importuji bankovní výpis?', 'How to import bank statements?', 'V sekci Banka klikněte na "Import transakcí". Podporujeme formáty CSV a ABO. Po importu můžete spárovat transakce s fakturami automaticky nebo ručně.', 'In Bank section click "Import transactions". We support CSV and ABO formats. After import you can match transactions with invoices automatically or manually.', '/bank', 'feature', 8],
  ['automatické párování,auto match,spárovat automaticky', 'Jak funguje automatické párování?', 'How does auto-matching work?', 'Klikněte na "Automatické párování" v sekci Banka. Systém porovná variabilní symboly a částky transakcí s fakturami a automaticky je spáruje.', 'Click "Auto-match" in Bank section. The system compares variable symbols and amounts of transactions with invoices and matches them automatically.', '/bank', 'feature', 7],
  ['qr,qr kód,platební qr,qr platba', 'Kde najdu QR kód?', 'Where is QR code?', 'QR kód pro platbu najdete v detailu vydané faktury. Obsahuje platební údaje (IBAN, částku, variabilní symbol) pro snadné zaplacení mobilním bankovnictvím.', 'Payment QR code is in the issued invoice detail. It contains payment details (IBAN, amount, variable symbol) for easy mobile banking payment.', '/invoices', 'feature', 7],
  ['bankovní účet,přidat účet,nový účet,bank account,účet pro měnu', 'Jak přidám bankovní účet?', 'How to add a bank account?', 'V sekci Banka klikněte na "Přidat účet". Zadejte název, číslo účtu, IBAN a měnu. Účty jsou rozděleny podle měny — pro každou měnu (CZK, EUR, USD…) může existovat právě jeden účet. Např. eurový účet pro platby v EUR, korunový pro CZK atd.', 'In Bank section click "Add account". Enter name, account number, IBAN and currency. Accounts are grouped by currency — each currency (CZK, EUR, USD…) can have exactly one account. E.g. a EUR account for euro payments, a CZK account for koruna payments etc.', '/bank', 'feature', 7],

  // ═══════════════════════════════════════
  // CLIENTS
  // ═══════════════════════════════════════
  ['nový klient,přidat klienta,vytvořit klienta,create client', 'Jak přidám nového klienta?', 'How to add a new client?', 'V sekci Klienti klikněte na "+ Nový klient". Vyplňte název, IČO, DIČ, adresu a kontaktní údaje. Klienta můžete také vytvořit přímo při vytváření faktury.', 'In Clients section click "+ New client". Fill in name, ID, VAT ID, address and contact details. You can also create a client directly when creating an invoice.', '/clients', 'feature', 8],
  ['ares,načíst z ares,vyhledat firmu,ičo vyhledat', 'Co je ARES vyhledávání?', 'What is ARES lookup?', 'ARES je registr ekonomických subjektů. Při přidávání klienta zadejte IČO a klikněte na "Načíst z ARES" — systém automaticky doplní název, adresu a DIČ z veřejného rejstříku.', 'ARES is the Czech business register. When adding a client, enter the ID number and click "Load from ARES" — the system auto-fills name, address and VAT ID from the public register.', '/clients', 'feature', 8],
  ['detail klienta,historie klienta,faktury klienta', 'Kde vidím historii klienta?', 'Where to see client history?', 'Klikněte na klienta v seznamu pro zobrazení detailu. Vidíte všechny jeho faktury, kontaktní údaje a poznámky. Můžete filtrovat faktury podle stavu.', 'Click on a client in the list to see their detail. You see all their invoices, contact info and notes. You can filter invoices by status.', '/clients', 'feature', 7],

  // ═══════════════════════════════════════
  // VAT / DPH
  // ═══════════════════════════════════════
  ['plátce dph,registrace dph,vat payer,neplátce', 'Jsem plátce DPH?', 'Am I a VAT payer?', 'Nastavení plátce/neplátce DPH najdete v Správa → Společnost → sekce DPH. Pokud jste plátce, faktury budou automaticky obsahovat DPH (sazby 0%, 12%, 21%).', 'VAT payer settings are in Admin → Company → VAT section. If you are a VAT payer, invoices will automatically include VAT (rates 0%, 12%, 21%).', '/company', 'feature', 8],
  ['sazba dph,daňová sazba,vat rate,21%,12%,0%', 'Jaké jsou sazby DPH?', 'What are VAT rates?', 'V ČR platí tři sazby DPH: základní 21%, snížená 12% a nulová 0% (pro osvobozená plnění). Sazbu nastavíte u každé položky faktury.', 'In Czech Republic there are three VAT rates: standard 21%, reduced 12% and zero 0% (for exempt supplies). Rate is set on each invoice item.', '/vat', 'terminology', 7],
  ['přiznání k dph,daňové přiznání,vat return,dph výkaz', 'Jak vytvořím přiznání k DPH?', 'How to create a VAT return?', 'V Účetnictví → DPH zvolte měsíc a rok a klikněte na "Generovat". Systém automaticky vytvoří přehled DPH ze všech faktur za dané období — vstupy, výstupy a rozdíl.', 'In Accounting → VAT select month and year and click "Generate". The system auto-creates a VAT overview from all invoices for the period — inputs, outputs and difference.', '/vat', 'feature', 8],
  ['kontrolní hlášení,control report', 'Co je kontrolní hlášení?', 'What is a control report?', 'Kontrolní hlášení je povinný měsíční výkaz pro plátce DPH v ČR. V sekci DPH najdete podklady pro jeho vyplnění na Daňovém portálu Finanční správy.', 'A control report is a mandatory monthly statement for VAT payers in CZ. In the VAT section you find data for filling it on the Tax Administration portal.', '/vat', 'terminology', 6],

  // ═══════════════════════════════════════
  // ACCOUNTING (Účetnictví)
  // ═══════════════════════════════════════
  ['účtová osnova,chart of accounts,účty,rozvahy,seznam účtů', 'Co je účtová osnova?', 'What is chart of accounts?', 'Účtová osnova je seznam všech účtů (aktiva, pasiva, náklady, výnosy, vlastní kapitál). V Účetnictví → Účtová osnova je můžete prohlížet, přidávat a upravovat. Tlačítkem "Seed" načtete výchozí českou osnovu.', 'Chart of accounts is a list of all accounts (assets, liabilities, expenses, revenue, equity). In Accounting → Chart of accounts you can view, add and edit. "Seed" button loads default Czech chart.', '/accounting', 'feature', 7],
  ['účetní deník,journal,žurnál,účetní zápis,journal entry', 'Jak vytvořím účetní zápis?', 'How to create a journal entry?', 'V Účetnictví → Deník klikněte na "Nový zápis". Zadejte datum, popis, a přidejte řádky s účty (MD/D). Celkový součet na straně Má dáti a Dal musí být vyrovnaný. Poté zápis zaúčtujte.', 'In Accounting → Journal click "New entry". Enter date, description, and add lines with accounts (debit/credit). Total debit and credit must balance. Then post the entry.', '/accounting', 'feature', 7],
  ['hlavní kniha,ledger,general ledger,obraty', 'Co je hlavní kniha?', 'What is the general ledger?', 'Hlavní kniha zobrazuje obraty a zůstatky na jednotlivých účtech. V Účetnictví najdete záložku Hlavní kniha s přehledem debetních a kreditních obratů za zvolené období.', 'The general ledger shows turnover and balances on individual accounts. In Accounting find the Ledger tab with debit and credit turnover overview for chosen period.', '/accounting', 'feature', 7],
  ['zaúčtovat,post entry,účtování,zaúčtování', 'Co znamená zaúčtovat?', 'What does posting mean?', 'Zaúčtování je potvrzení účetního zápisu. Po zaúčtování se zápis promítne do obratů v hlavní knize a nelze ho už běžně upravovat (pouze stornovat a vytvořit nový).', 'Posting is confirming a journal entry. After posting, the entry affects ledger balances and cannot be normally edited (only cancelled and recreated).', '/accounting', 'terminology', 6],
  ['účetní období,fiscal period,uzávěrka,měsíční uzávěrka', 'Co je účetní období?', 'What is a fiscal period?', 'Účetní období (obvykle měsíc) lze uzavřít, čímž se zamezí zpětným úpravám záznamů. Uzávěrky najdete v nastavení účetnictví.', 'A fiscal period (usually month) can be closed, preventing retroactive changes. Period closings are in accounting settings.', '/accounting', 'terminology', 6],

  // ═══════════════════════════════════════
  // CASH REGISTER (Pokladna)
  // ═══════════════════════════════════════
  ['pokladna,pokladní doklad,cash register,hotovost,cash', 'Kde najdu pokladnu?', 'Where is the cash register?', 'Pokladnu najdete v Účetnictví → Pokladna (přidejte ji do navigace pokud chybí). Můžete spravovat pokladní knihu, příjmové a výdajové doklady a sledovat zůstatek hotovosti.', 'Cash register is in Accounting section. You can manage the cash book, income and expense documents and track cash balance.', '/bank', 'feature', 6],
  ['příjmový doklad,ppd,pokladní příjem', 'Co je příjmový pokladní doklad?', 'What is a cash receipt?', 'Příjmový pokladní doklad (PPD) zaznamenává příjem hotovosti do pokladny — např. platba od zákazníka. Vytvořte ho v sekci Pokladna → Nový doklad → Příjem.', 'A cash receipt (PPD) records cash income — e.g. customer payment. Create it in Cash Register → New document → Income.', '/bank', 'feature', 6],

  // ═══════════════════════════════════════
  // PRODUCTS & STOCK
  // ═══════════════════════════════════════
  ['produkt,produkty,služba,služby,zboží,products,katalog', 'Kde spravuji produkty?', 'Where to manage products?', 'Produkty a služby spravujete v katalogu Produkty. Každý produkt má název, SKU, jednotku, cenu, nákupní cenu a sazbu DPH. Můžete je pak snadno vybírat při vytváření faktur.', 'Products and services are in the Products catalog. Each product has name, SKU, unit, price, purchase price and VAT rate. You can easily select them when creating invoices.', '/bank', 'feature', 6],
  ['sklad,zásoby,stock,inventory,skladové zásoby', 'Jak sleduji skladové zásoby?', 'How to track inventory?', 'V sekci Produkty vidíte skladové zásoby, minimální hladiny a pohyby (příjem, výdej, inventura). Systém vás upozorní, když zásoba klesne pod minimum.', 'In Products section you see stock levels, minimum thresholds and movements (in, out, adjustment). The system alerts when stock drops below minimum.', '/bank', 'feature', 6],

  // ═══════════════════════════════════════
  // USERS, ROLES & PERMISSIONS
  // ═══════════════════════════════════════
  ['role,oprávnění,permissions,přístup,práva', 'Jaké jsou role v systému?', 'What are the system roles?', 'Systém má 4 základní role:\n• Administrátor — plný přístup, správa uživatelů a nastavení\n• Účetní — faktury, evidence, účetnictví, ale ne správa uživatelů\n• Manažer — čtení a schvalování, omezená editace\n• Náhled — pouze čtení bez možnosti editace', 'The system has 4 basic roles:\n• Admin — full access, user management and settings\n• Accountant — invoices, evidence, accounting, but not user management\n• Manager — read and approve, limited editing\n• Viewer — read-only access', '/users', 'feature', 8],
  ['přidat uživatele,nový uživatel,pozvat,invite,registrace uživatele', 'Jak přidám nového uživatele?', 'How to add a new user?', 'V Správa → Uživatelé klikněte na "Přidat uživatele". Zadejte jméno, email, heslo a roli. Alternativně můžete sdílet kód pozvánky — nový uživatel se zaregistruje a vy ho schválíte.', 'In Admin → Users click "Add user". Enter name, email, password and role. Alternatively share the invite code — new user registers and you approve them.', '/users', 'feature', 8],
  ['pozvánka,invite code,kód pozvánky,zvací kód', 'Co je kód pozvánky?', 'What is an invite code?', 'Kód pozvánky umožňuje novým uživatelům se zaregistrovat do vašeho tenanta. Najdete ho v nastavení nebo u SuperAdmina. Uživatel zadá kód při registraci a administrátor ho pak schválí.', 'An invite code allows new users to register to your tenant. Find it in settings or SuperAdmin. User enters the code during registration and admin approves them.', '/users', 'feature', 6],
  ['změnit heslo,reset hesla,zapomenuté heslo,forgot password', 'Jak změním heslo?', 'How to change password?', 'Své heslo změníte v Můj profil → Změna hesla. Pokud jste heslo zapomněli, na přihlašovací stránce klikněte na "Zapomenuté heslo" a zadejte email pro reset.', 'Change your password in My Profile → Change password. If you forgot it, click "Forgot password" on the login page and enter your email for reset.', '/profile', 'feature', 8],
  ['skupina uživatelů,user group,týmy,teams', 'Co jsou skupiny uživatelů?', 'What are user groups?', 'Skupiny uživatelů umožňují organizovat lidi do týmů a přiřazovat jim společná oprávnění. Administrátor je spravuje v sekci Uživatelé.', 'User groups let you organize people into teams and assign shared permissions. Admin manages them in the Users section.', '/users', 'feature', 6],

  // ═══════════════════════════════════════
  // COMPANY SETTINGS
  // ═══════════════════════════════════════
  ['logo,nahrát logo,company logo,firemní logo', 'Jak nahraji logo společnosti?', 'How to upload company logo?', 'V Správa → Společnost najdete sekci "Logo společnosti". Přetáhněte obrázek (PNG/JPG) nebo klikněte pro nahrání. Logo se zobrazí na všech fakturách a PDF dokumentech.', 'In Admin → Company find "Company logo" section. Drag an image (PNG/JPG) or click to upload. The logo appears on all invoices and PDF documents.', '/company', 'feature', 7],
  ['vzhled faktury,layout,šablona,template,design faktury', 'Jak změním vzhled faktur?', 'How to change invoice layout?', 'V Správa → Společnost najdete sekci "Vzhled faktury" s 5 layouty: Klasický, Minimalistický, Korporátní, Elegantní a Kompaktní. Najeďte myší pro náhled a klikněte pro výběr.', 'In Admin → Company find "Invoice layout" with 5 layouts: Classic, Minimal, Corporate, Elegant and Compact. Hover for preview and click to select.', '/company', 'feature', 7],
  ['bankovní spojení,bank details,číslo účtu,iban,swift', 'Kde nastavím bankovní spojení?', 'Where to set bank details?', 'V Správa → Společnost → Bankovní údaje. Zadejte číslo účtu, kód banky, IBAN a SWIFT. Tyto údaje se automaticky zobrazují na fakturách.', 'In Admin → Company → Bank details. Enter account number, bank code, IBAN and SWIFT. These details automatically appear on invoices.', '/company', 'feature', 8],
  ['záloha databáze,backup,export dat,zálohování', 'Jak zálohuji data?', 'How to backup data?', 'V Správa → Společnost → Správa dat klikněte na "Stáhnout zálohu databáze". Stáhne se kompletní SQLite soubor se všemi daty. Doporučujeme zálohovat pravidelně.', 'In Admin → Company → Data management click "Download database backup". A complete SQLite file with all data is downloaded. We recommend regular backups.', '/company', 'feature', 7],
  ['splatnost,default due days,výchozí splatnost,dnů splatnost', 'Jak nastavím výchozí splatnost?', 'How to set default due days?', 'V Správa → Společnost → Fakturace nastavte "Výchozí splatnost (dnů)". Toto číslo se automaticky použije při vytváření nové faktury pro výpočet data splatnosti.', 'In Admin → Company → Invoicing set "Default due days". This number is automatically used when creating a new invoice to calculate the due date.', '/company', 'feature', 6],

  // ═══════════════════════════════════════
  // SEARCH & NAVIGATION
  // ═══════════════════════════════════════
  ['hledat,vyhledat,search,najít,find,ctrl+k', 'Jak vyhledávám?', 'How to search?', 'Použijte vyhledávací pole v horní liště (zkratka Ctrl+K nebo Cmd+K na Macu). Vyhledávání prohledává faktury (číslo, klient), klienty (název, IČO) a evidence (název). Výsledky se zobrazují ihned při psaní.', 'Use the search field in the top bar (Ctrl+K or Cmd+K on Mac). Search covers invoices (number, client), clients (name, ID) and evidence (title). Results appear instantly as you type.', null, 'feature', 9],
  ['tmavý režim,dark mode,noční režim,theme,světlý', 'Jak přepnu tmavý režim?', 'How to toggle dark mode?', 'Klikněte na ikonu měsíce (🌙) v pravém horním rohu topbaru. Nastavení se uloží a přetrvá i po zavření prohlížeče.', 'Click the moon icon (🌙) in the top right corner of the topbar. Setting is saved and persists after closing the browser.', null, 'feature', 7],
  ['klávesové zkratky,keyboard shortcuts,zkratky', 'Jaké jsou klávesové zkratky?', 'What keyboard shortcuts are there?', 'Hlavní zkratka: Ctrl+K (Cmd+K) pro globální vyhledávání. V editorech fungují standardní zkratky prohlížeče (Ctrl+S pro uložení formuláře).', 'Main shortcut: Ctrl+K (Cmd+K) for global search. In editors standard browser shortcuts work (Ctrl+S for form submit).', null, 'feature', 6],
  ['mobilní,telefon,responsive,tablet,mobil', 'Funguje systém na mobilu?', 'Does it work on mobile?', 'Ano, systém je plně responzivní. Na mobilu se postranní panel skryje a otevřete ho kliknutím na ikonu menu (☰). Všechny funkce jsou dostupné i na telefonu a tabletu.', 'Yes, the system is fully responsive. On mobile the sidebar hides and you open it by clicking the menu icon (☰). All features are available on phone and tablet.', null, 'feature', 6],

  // ═══════════════════════════════════════
  // TERMINOLOGY — accounting concepts
  // ═══════════════════════════════════════
  ['co je ičo,ičo,identifikační číslo,ico,identification number', 'Co je IČO?', 'What is IČO?', 'IČO (Identifikační číslo osoby) je osmimístné číslo identifikující podnikatele nebo právnickou osobu v ČR. Přiděluje ho rejstříkový soud nebo živnostenský úřad. Zadejte ho v nastavení společnosti.', 'IČO (Identification Number) is an 8-digit number identifying a business entity in Czech Republic. It is assigned by the court or trade office. Enter it in company settings.', '/company', 'terminology', 6],
  ['co je dič,dič,daňové identifikační číslo,tax id,vat id', 'Co je DIČ?', 'What is DIČ?', 'DIČ (Daňové identifikační číslo) identifikuje plátce DPH. V ČR má formát CZ + IČO (např. CZ12345678). Zadejte ho v nastavení společnosti pokud jste plátce DPH.', 'DIČ (Tax Identification Number) identifies VAT payers. In CZ it is CZ + IČO (e.g. CZ12345678). Enter it in company settings if you are a VAT payer.', '/company', 'terminology', 6],
  ['co je iban,iban,mezinárodní číslo účtu', 'Co je IBAN?', 'What is IBAN?', 'IBAN (International Bank Account Number) je mezinárodní formát čísla účtu. V ČR začíná "CZ" a má 24 znaků (např. CZ6508000000192000145399). Potřebujete ho pro zahraniční platby.', 'IBAN (International Bank Account Number) is the international account number format. In CZ it starts with "CZ" and has 24 characters. You need it for international payments.', '/company', 'terminology', 6],
  ['co je swift,swift,bic,swift kód', 'Co je SWIFT/BIC?', 'What is SWIFT/BIC?', 'SWIFT (Society for Worldwide Interbank Financial Telecommunication) nebo BIC je kód identifikující banku pro mezinárodní převody. Např. GIBACZPX pro Českou spořitelnu.', 'SWIFT or BIC is a code identifying a bank for international transfers. E.g. GIBACZPX for Česká spořitelna.', '/company', 'terminology', 5],
  ['základ daně,tax base,zdanitelné plnění', 'Co je základ daně?', 'What is the tax base?', 'Základ daně je částka, ze které se počítá DPH. Např. při ceně 1 000 Kč bez DPH je základ 1 000 Kč a DPH 21% činí 210 Kč. Celkem s DPH = 1 210 Kč.', 'Tax base is the amount from which VAT is calculated. E.g. for 1,000 CZK excl. VAT, base is 1,000 CZK and 21% VAT is 210 CZK. Total incl. VAT = 1,210 CZK.', null, 'terminology', 5],
  ['příjmy,revenue,tržby,obrat,turnover', 'Co jsou tržby/obrat?', 'What is revenue?', 'Obrat je celková hodnota vydaných faktur za dané období. Na Dashboardu vidíte graf s příjmy a výdaji po měsících. Můžete filtrovat za různá období.', 'Revenue is the total value of issued invoices for a period. On the Dashboard you see a chart with income and expenses by month. You can filter for different periods.', '/', 'terminology', 6],
  ['náklad,expense,výdaj,costs', 'Co jsou náklady?', 'What are expenses?', 'Náklady jsou výdaje firmy — přijaté faktury, nákupy, služby apod. Zaznamenávejte je v sekci Evidence jako typ "Výdaj" pro přehled o hospodaření.', 'Expenses are company costs — received invoices, purchases, services etc. Record them in Evidence as "Expense" type for financial overview.', '/evidence', 'terminology', 5],
  ['majetek,asset,dlouhodobý majetek,odpisy', 'Jak eviduji majetek?', 'How to track assets?', 'Majetek (hardware, vybavení, auta) evidujte v sekci Evidence jako typ "Majetek". Zadejte pořizovací cenu, datum a popis. Pro odpisy používejte účetní deník.', 'Track assets (hardware, equipment, cars) in Evidence as "Asset" type. Enter purchase price, date and description. Use accounting journal for depreciation.', '/evidence', 'feature', 5],
  ['pohledávka,receivable,dlužná částka', 'Co je pohledávka?', 'What is a receivable?', 'Pohledávka je částka, kterou vám dluží klient za vydanou fakturu. Na Dashboardu vidíte přehled stárnutí pohledávek — faktury po splatnosti rozdělené podle stáří (0-30, 30-60, 60-90, 90+ dnů).', 'A receivable is an amount owed to you by a client for an issued invoice. On the Dashboard you see the aging report — overdue invoices grouped by age (0-30, 30-60, 60-90, 90+ days).', '/', 'terminology', 6],
  ['závazek,payable,dlužíme', 'Co je závazek?', 'What is a payable?', 'Závazek je částka, kterou vaše firma dluží dodavateli za přijatou fakturu. Evidujte přijaté faktury se stavem "Po splatnosti" pro přehled o závazcích.', 'A payable is an amount your company owes to a supplier for a received invoice. Track received invoices with "Overdue" status for payables overview.', '/invoices', 'terminology', 5],
  ['cash flow,peněžní tok,tok hotovosti', 'Co je cash flow?', 'What is cash flow?', 'Cash flow (peněžní tok) je přehled příjmů a výdajů za období. Na Dashboardu vidíte graf příjmů vs. výdajů. Pozitivní cash flow znamená, že přijmete více než vydáte.', 'Cash flow is an overview of income and expenses over a period. On the Dashboard you see income vs expenses chart. Positive cash flow means you receive more than you spend.', '/', 'terminology', 5],

  // ═══════════════════════════════════════
  // TROUBLESHOOTING
  // ═══════════════════════════════════════
  ['nemohu vytvořit,nejde,nefunguje,chyba,error,problém,bug', 'Mám problém se systémem', 'I have a problem', 'Pokud narazíte na problém:\n1. Zkuste obnovit stránku (F5 nebo Ctrl+R)\n2. Zkontrolujte, zda máte správnou roli/oprávnění\n3. Ověřte, že jsou vyplněna všechna povinná pole\n4. Zkuste se odhlásit a znovu přihlásit\nPokud problém přetrvává, kontaktujte administrátora.', 'If you encounter a problem:\n1. Refresh the page (F5 or Ctrl+R)\n2. Check your role/permissions\n3. Verify all required fields are filled\n4. Try logging out and back in\nIf the problem persists, contact administrator.', null, 'help', 6],
  ['nemám přístup,access denied,oprávnění chybí,zakázáno,forbidden', 'Nemám přístup k funkci', 'I don\'t have access', 'Přístup k funkcím závisí na vaší roli. Administrátor má plný přístup, účetní má přístup k fakturám a účetnictví, manažer má omezenou editaci a role Náhled je pouze pro čtení. Kontaktujte administrátora pro změnu oprávnění.', 'Access depends on your role. Admin has full access, accountant can access invoices and accounting, manager has limited editing, Viewer is read-only. Contact admin to change permissions.', '/users', 'help', 7],
  ['stránka se nenačítá,blank page,bílá stránka,loading', 'Stránka se nenačítá', 'Page is not loading', 'Zkuste:\n1. Obnovit stránku (Ctrl+R nebo F5)\n2. Vymazat cache prohlížeče (Ctrl+Shift+Delete)\n3. Zkusit jiný prohlížeč\n4. Ověřit připojení k internetu\nPokud problém přetrvává, kontaktujte administrátora.', 'Try:\n1. Refresh page (Ctrl+R or F5)\n2. Clear browser cache (Ctrl+Shift+Delete)\n3. Try different browser\n4. Check internet connection\nIf problem persists, contact admin.', null, 'help', 6],
  ['exportovat,export,csv,xlsx,stáhnout data,download data', 'Jak exportuji data?', 'How to export data?', 'Data můžete exportovat v různých sekcích: faktury, klienty a evidenci. Hledejte tlačítko "Export" nebo "Stáhnout". Podporujeme formáty CSV a PDF.', 'You can export data in various sections: invoices, clients and evidence. Look for "Export" or "Download" button. We support CSV and PDF formats.', '/invoices', 'feature', 6],
  ['superadmin,super admin,správce systému,system admin', 'Co je SuperAdmin?', 'What is SuperAdmin?', 'SuperAdmin je systémový správce s přístupem ke všem tenantům. Spravuje organizace, může vytvářet a mazat tenanty. Přihlašuje se na speciální stránce.', 'SuperAdmin is a system administrator with access to all tenants. Manages organizations, can create and delete tenants. Logs in on a special page.', null, 'feature', 5],
  ['tenant,organizace,firma,multitenant', 'Co je tenant?', 'What is a tenant?', 'Tenant je organizace/firma v systému. Každý tenant má své vlastní data — faktury, klienty, nastavení. Data jsou striktně oddělená. Systém podporuje více tenantů (firem) současně.', 'A tenant is an organization/company in the system. Each tenant has its own data — invoices, clients, settings. Data is strictly separated. The system supports multiple tenants simultaneously.', null, 'terminology', 5],

  // ═══════════════════════════════════════
  // GENERAL HELP & GREETINGS
  // ═══════════════════════════════════════
  ['ahoj,dobrý den,čau,nazdar,hello,hi,hey,zdravím', 'Pozdrav', 'Greeting', 'Ahoj! Jsem Hyňa, váš chytrý asistent. Pomohu vám s navigací v systému, zodpovím otázky o fakturách, klientech, účetnictví a dalších funkcích. Na co se chcete zeptat?', 'Hello! I am Hyňa, your smart assistant. I help with system navigation, answer questions about invoices, clients, accounting and other features. What would you like to know?', null, 'help', 10],
  ['pomoc,help,nápověda,nevím,neumím,kde začít,začátečník', 'Potřebuji pomoct', 'I need help', 'Jsem Hyňa a pomohu vám! Můžete se mě zeptat na:\n• Navigaci — kde co najdu v systému\n• Faktury — jak vytvořit, odeslat, zaplatit\n• Klienty — správa kontaktů\n• Účetnictví — DPH, deník, hlavní kniha\n• Nastavení — firma, uživatelé, role\n• Aktuální data — kolik mám faktur, obraty, po splatnosti\nNebo se ptejte vlastními slovy!', 'I am Hyňa and I will help! You can ask about:\n• Navigation — where to find things\n• Invoices — create, send, pay\n• Clients — contact management\n• Accounting — VAT, journal, ledger\n• Settings — company, users, roles\n• Live data — invoice count, revenue, overdue\nOr ask in your own words!', null, 'help', 10],
  ['děkuji,díky,thanks,thank you,dík,díky moc', 'Poděkování', 'Thanks', 'Nemáte zač! Jsem tu kdykoliv budete potřebovat pomoct. Stačí se zeptat!', 'You\'re welcome! I\'m here whenever you need help. Just ask!', null, 'help', 8],
  ['co umíš,co zvládneš,schopnosti,funkce chatbota', 'Co umíš?', 'What can you do?', 'Umím:\n• Navigovat vás po systému — řeknu kde co najdete\n• Zodpovídat otázky o fakturách, účetnictví, DPH\n• Zobrazit živá data — počty faktur, obraty, dluhy\n• Vysvětlit účetní pojmy (IČO, DIČ, IBAN, DPH...)\n• Poradit s řešením problémů\nA neustále se učím nové věci!', 'I can:\n• Navigate you around the system\n• Answer questions about invoices, accounting, VAT\n• Show live data — invoice counts, revenue, debts\n• Explain accounting terms\n• Help troubleshoot problems\nAnd I keep learning new things!', null, 'help', 9],
  ['kdo jsi,co jsi,jak se jmenuješ,who are you', 'Kdo jsi?', 'Who are you?', 'Jsem Hyňa — inteligentní asistent ERP systému Rainbow Family Investment. Pomohu vám s čímkoliv v aplikaci. Rozumím česky i anglicky a mám přístup k živým datům systému!', 'I am Hyňa — an intelligent ERP assistant for Rainbow Family Investment. I help with anything in the application. I understand Czech and English and have access to live system data!', null, 'help', 9],

  // ═══════════════════════════════════════
  // ADVANCED / SPECIFIC SCENARIOS
  // ═══════════════════════════════════════
  ['zahraniční faktura,foreign invoice,cizí měna,eur faktura', 'Jak vystavím fakturu v cizí měně?', 'How to issue a foreign currency invoice?', 'Při vytváření faktury vyberte měnu (EUR, USD, GBP, PLN). Systém automaticky přepočte částku na CZK podle aktuálního kurzu ČNB. Faktura se vygeneruje v dané měně s přepočtem.', 'When creating an invoice select currency (EUR, USD, GBP, PLN). The system auto-converts to CZK using current CNB rate. Invoice is generated in that currency with conversion.', '/invoices/new', 'feature', 7],
  ['datum zdanitelného plnění,supply date,duzp,dpp', 'Co je datum zdanitelného plnění?', 'What is the supply date?', 'Datum zdanitelného plnění (DUZP/DPP) je datum, kdy došlo k dodání zboží nebo služby. Může se lišit od data vystavení faktury. Nastavíte ho v detailu faktury.', 'Supply date (DUZP) is the date when goods or services were delivered. It may differ from the invoice issue date. Set it in invoice detail.', '/invoices', 'terminology', 6],
  ['způsob platby,payment method,převod,hotově,kartou', 'Jaké způsoby platby existují?', 'What payment methods are available?', 'Systém podporuje: bankovní převod, hotovost, platební karta a dobírka. Výchozí způsob je bankovní převod. Nastavíte ho při vytváření faktury.', 'The system supports: bank transfer, cash, credit card and COD. Default method is bank transfer. Set it when creating an invoice.', '/invoices/new', 'feature', 6],
  ['audit log,historie změn,log,záznam změn', 'Kde vidím historii změn?', 'Where is the audit log?', 'Audit log (záznam změn) je dostupný pro administrátory a zaznamenává všechny důležité akce v systému — vytvoření, editaci a smazání faktur, klientů a dalších záznamů.', 'Audit log is available to admins and records all important actions — creation, editing and deletion of invoices, clients and other records.', '/company', 'feature', 5],
  ['elektronický podpis,podpis,signature,digitální podpis', 'Jak nastavím elektronický podpis?', 'How to set up signature?', 'V Můj profil → Podpis můžete nakreslit nebo nahrát svůj elektronický podpis. Podpis se pak automaticky zobrazuje na fakturách.', 'In My Profile → Signature you can draw or upload your electronic signature. The signature then automatically appears on invoices.', '/profile', 'feature', 6],
  ['opakovaná faktura interval,jak často,frekvence', 'Jaké intervaly mají opakované faktury?', 'What recurring invoice intervals are available?', 'Opakované faktury podporují 4 intervaly:\n• Týdně — každých 7 dní\n• Měsíčně — každý měsíc\n• Čtvrtletně — každé 3 měsíce\n• Ročně — jednou za rok\nMůžete nastavit datum začátku a volitelný konec.', 'Recurring invoices support 4 intervals:\n• Weekly — every 7 days\n• Monthly — every month\n• Quarterly — every 3 months\n• Yearly — once a year\nSet start date and optional end date.', '/recurring', 'feature', 6],
  ['kategorie,categories,category rules,pravidla', 'Co jsou kategorie a pravidla?', 'What are categories and rules?', 'Kategorie automaticky třídí evidence (výdaje, příjmy) podle klíčových slov. V nastavení můžete vytvořit pravidla — např. "hosting" → kategorie "IT". Systém pak automaticky kategorizuje nové záznamy.', 'Categories automatically sort evidence (expenses, income) by keywords. In settings you can create rules — e.g. "hosting" → category "IT". The system then auto-categorizes new records.', '/evidence', 'feature', 5],
  ['objednávka,objednávky,orders,přijatá objednávka', 'Kde najdu objednávky?', 'Where are orders?', 'Objednávky spravujete v sekci objednávek. Můžete vytvářet přijaté i vydané objednávky a po dokončení je převést na faktury.', 'Orders are managed in the orders section. You can create received and issued orders and convert them to invoices when completed.', '/invoices', 'feature', 5],
  ['čnb,česká národní banka,cnb,aktualizace kurzů', 'Jak se aktualizují kurzy?', 'How are exchange rates updated?', 'Kurzovní lístek se automaticky stahuje z České národní banky (ČNB) každých 6 hodin. Můžete také ručně spustit aktualizaci tlačítkem "Obnovit kurzy" v sekci Měny.', 'Exchange rates are automatically downloaded from the Czech National Bank (CNB) every 6 hours. You can also manually trigger an update with "Refresh rates" in Currencies.', '/currencies', 'feature', 6],

  // ═══════════════════════════════════════
  // REVERSE CHARGE / PŘENESENÍ DPH
  // ═══════════════════════════════════════
  ['přenesení daňové povinnosti,reverse charge,přenesená,reverse,tuzemské přenesení', 'Co je přenesení daňové povinnosti?', 'What is reverse charge?', 'Přenesení daňové povinnosti (reverse charge) znamená, že DPH neodvádí dodavatel, ale odběratel. Používá se u stavebních prací, dodání zlata, emisních povolenek a dalších. Na faktuře uveďte "Daň odvede zákazník" a nulovou sazbu DPH.', 'Reverse charge means VAT is paid by the buyer, not the seller. Used for construction work, gold supply, emission permits and others. On the invoice state "Customer will account for tax" with zero VAT rate.', '/invoices/new', 'terminology', 7],
  ['třístranný obchod,triangulace,triangulation,eu obchod', 'Co je třístranný obchod?', 'What is triangulation?', 'Třístranný obchod je situace, kdy tři subjekty ze tří různých zemí EU obchodují a zboží jde přímo od prvního k třetímu. Prostřední subjekt neplatí DPH v zemi dodání. Vyžaduje speciální označení na faktuře.', 'Triangulation is when three parties from three EU countries trade and goods go directly from first to third. The middle party does not pay VAT in the delivery country. Requires special marking on invoice.', '/invoices', 'terminology', 5],

  // ═══════════════════════════════════════
  // PAYMENT TERMS & CONDITIONS
  // ═══════════════════════════════════════
  ['platební podmínky,payment terms,net 30,splatnost 30,podmínky platby', 'Jaké platební podmínky mohu nastavit?', 'What payment terms can I set?', 'Výchozí splatnost nastavíte v Správa → Společnost (počet dnů od vystavení). Běžné jsou 14, 30 nebo 60 dnů. Při vytváření faktury můžete splatnost změnit individuálně.', 'Default payment terms are set in Admin → Company (days from issue). Common are 14, 30 or 60 days. When creating an invoice you can change the due date individually.', '/company', 'feature', 7],
  ['penále,úroky z prodlení,late payment penalty,sankce za pozdní platbu,pokuta za nezaplacení,účtovat penále', 'Mohu účtovat penále za pozdní platbu?', 'Can I charge late payment penalties?', 'Ano, u faktur po splatnosti můžete vystavit penalizační fakturu s úroky z prodlení. Zákonná sazba je repo sazba ČNB + 8%. Vytvořte novou fakturu s popisem penále a odkazem na původní fakturu.', 'Yes, for overdue invoices you can issue a penalty invoice with late payment interest. Legal rate is CNB repo rate + 8%. Create a new invoice with penalty description referencing the original.', '/invoices/new', 'feature', 7],
  ['skonto,sleva za včasnou platbu,early payment discount,discount', 'Co je skonto?', 'What is an early payment discount?', 'Skonto je sleva za včasnou platbu (např. 2% sleva při zaplacení do 10 dnů). Uveďte podmínky skonta v poznámce faktury. Při zaplacení se slevou vytvořte dobropis na rozdíl.', 'A skonto is a discount for early payment (e.g. 2% discount if paid within 10 days). State skonto terms in the invoice note. If paid with discount, create a credit note for the difference.', '/invoices', 'feature', 5],

  // ═══════════════════════════════════════
  // LEGAL REQUIREMENTS (Czech)
  // ═══════════════════════════════════════
  ['náležitosti faktury,povinné údaje,legal requirements,co musí faktura obsahovat,zákonné', 'Co musí faktura povinně obsahovat?', 'What must an invoice contain?', 'Česká faktura musí obsahovat:\n• Označení dodavatele a odběratele (název, sídlo, IČO)\n• DIČ (pokud jste plátce DPH)\n• Číslo faktury\n• Datum vystavení a zdanitelného plnění\n• Popis zboží/služby\n• Základ daně, sazbu a výši DPH\n• Celkovou částku\nSystém tyto údaje vyplňuje automaticky.', 'A Czech invoice must contain:\n• Supplier and buyer info (name, address, ID)\n• VAT ID (if VAT payer)\n• Invoice number\n• Issue date and supply date\n• Description of goods/services\n• Tax base, rate and VAT amount\n• Total amount\nThe system fills these automatically.', '/invoices', 'terminology', 8],
  ['lhůta vystavení,15 dnů,deadline,do kdy vystavit', 'Do kdy musím vystavit fakturu?', 'By when must I issue an invoice?', 'Plátce DPH musí vystavit daňový doklad do 15 dnů od data zdanitelného plnění. Systém vás upozorní, pokud se blíží lhůta. Neplátci nemají zákonnou lhůtu, ale doporučujeme fakturovat ihned.', 'A VAT payer must issue a tax document within 15 days from the supply date. The system alerts you when the deadline approaches. Non-VAT payers have no legal deadline, but we recommend invoicing immediately.', '/invoices', 'terminology', 6],
  ['archivace,uchovávání,retention,jak dlouho uchovávat,jak dlouho uchovavat,archiv,jak dlouho,uchovavat faktury', 'Jak dlouho musím uchovávat faktury?', 'How long must I keep invoices?', 'Podle českého zákona musíte uchovávat daňové doklady minimálně 10 let. Účetní doklady se archivují 5 let (některé 10 let). Systém data uchovává automaticky — doporučujeme pravidelné zálohy.', 'Under Czech law you must keep tax documents for at least 10 years. Accounting documents are archived for 5 years (some 10 years). The system stores data automatically — we recommend regular backups.', '/company', 'terminology', 6],
  ['zaokrouhlení,rounding,haléřové vyrovnání,zaokrouhlit', 'Jak funguje zaokrouhlení na faktuře?', 'How does invoice rounding work?', 'Při platbě v hotovosti se celková částka zaokrouhlí na celé koruny. Zaokrouhlení se zobrazí jako samostatná položka na faktuře. Při bezhotovostní platbě se nezaokrouhluje.', 'For cash payments the total is rounded to whole CZK. Rounding appears as a separate item on the invoice. For bank transfers no rounding is applied.', '/invoices', 'terminology', 5],

  // ═══════════════════════════════════════
  // DATA MIGRATION & IMPORT
  // ═══════════════════════════════════════
  ['migrace dat,přenos dat,data migration,import dat,přejít z jiného systému', 'Jak přenesu data z jiného systému?', 'How to migrate data from another system?', 'Pro import dat: exportujte data z původního systému do CSV a použijte import v příslušné sekci (Klienti, Banka). Pro hromadný import faktur kontaktujte administrátora. Data ze systémů Pohoda, Money S3, ISDOC je možné importovat.', 'To import data: export from your old system to CSV and use import in the relevant section (Clients, Bank). For bulk invoice import contact administrator. Data from Pohoda, Money S3, ISDOC can be imported.', '/company', 'feature', 6],
  ['csv import,importovat csv,csv soubor,csv formát', 'Jak importuji CSV soubor?', 'How to import a CSV file?', 'CSV soubory můžete importovat v sekci Banka (bankovní výpisy) a Klienti. Soubor musí mít správné sloupce (záhlaví). Podporujeme kódování UTF-8 a Windows-1250. Po nahrání ověřte mapování sloupců.', 'CSV files can be imported in Bank (bank statements) and Clients sections. File must have correct columns (headers). We support UTF-8 and Windows-1250 encoding. After upload verify column mapping.', '/bank', 'feature', 6],

  // ═══════════════════════════════════════
  // BANK RECONCILIATION
  // ═══════════════════════════════════════
  ['rekonciliace,odsouhlasení,bank reconciliation,srovnání,zůstatek účtu', 'Co je bankovní rekonciliace?', 'What is bank reconciliation?', 'Bankovní rekonciliace je proces srovnání zůstatku v systému se skutečným stavem na bankovním účtu. V sekci Banka porovnejte importované transakce s fakturami. Spárované transakce potvrzují správnost.', 'Bank reconciliation is the process of matching system balance with actual bank account balance. In Bank section compare imported transactions with invoices. Matched transactions confirm accuracy.', '/bank', 'feature', 6],
  ['nespárované transakce,neidentifikované,unmatched,nepřiřazené', 'Co dělat s nespárovanými transakcemi?', 'What to do with unmatched transactions?', 'Nespárované transakce najdete v sekci Banka. Můžete je:\n• Ručně spárovat s fakturou (klikněte na "Spárovat")\n• Vytvořit nový záznam v evidenci\n• Označit jako interní převod\n• Ignorovat (např. bankovní poplatky)', 'Unmatched transactions are in Bank section. You can:\n• Manually match with an invoice (click "Match")\n• Create a new evidence record\n• Mark as internal transfer\n• Ignore (e.g. bank fees)', '/bank', 'feature', 5],

  // ═══════════════════════════════════════
  // REPORTS & ANALYTICS
  // ═══════════════════════════════════════
  ['výkaz,report,výsledovka,p&l,profit and loss,zisk a ztráta', 'Kde najdu výkaz zisků a ztrát?', 'Where is the P&L report?', 'Výkaz zisků a ztrát (výsledovku) najdete v Účetnictví → Hlavní kniha. Porovnejte nákladové účty (5xx) s výnosovými účty (6xx). Dashboard také zobrazuje graf příjmů vs. výdajů.', 'The P&L statement is in Accounting → General Ledger. Compare expense accounts (5xx) with revenue accounts (6xx). Dashboard also shows an income vs expenses chart.', '/accounting', 'feature', 6],
  ['rozvaha,balance sheet,bilance,aktiva pasiva', 'Kde najdu rozvahu?', 'Where is the balance sheet?', 'Rozvahu (bilanci) najdete v Účetnictví → Hlavní kniha. Aktiva jsou účty třídy 0-3, pasiva třídy 4. Rozvaha ukazuje finanční pozici firmy k danému datu.', 'The balance sheet is in Accounting → General Ledger. Assets are account classes 0-3, liabilities class 4. Balance sheet shows the company financial position at a given date.', '/accounting', 'feature', 6],
  ['přehled,statistiky,analytics,stats,grafy,chart', 'Kde vidím statistiky a přehledy?', 'Where to see statistics?', 'Na Dashboardu najdete:\n• Graf příjmů a výdajů po měsících\n• Stav faktur (koláčový graf)\n• Top 5 klientů podle obratu\n• Stárnutí pohledávek\n• Celkový obrat a nezaplacené faktury\nDalší přehledy v Účetnictví → Hlavní kniha.', 'On the Dashboard you find:\n• Monthly income/expense chart\n• Invoice status (pie chart)\n• Top 5 clients by revenue\n• Aging report\n• Total revenue and unpaid invoices\nMore reports in Accounting → Ledger.', '/', 'feature', 7],

  // ═══════════════════════════════════════
  // DUPLICATE / CONCURRENT EDITING
  // ═══════════════════════════════════════
  ['duplicitní faktura,duplikát,stejná faktura,duplicity', 'Jak zabráním duplicitním fakturám?', 'How to prevent duplicate invoices?', 'Systém automaticky přiděluje unikátní čísla faktur v číselné řadě. Pokud potřebujete zkontrolovat duplicity, použijte vyhledávání (Ctrl+K) a hledejte podle klienta nebo částky.', 'The system automatically assigns unique invoice numbers in the number series. To check duplicates, use search (Ctrl+K) and search by client or amount.', '/invoices', 'feature', 5],
  ['současná editace,concurrent,více uživatelů,kolize', 'Mohou více uživatelů editovat současně?', 'Can multiple users edit simultaneously?', 'Ano, více uživatelů může pracovat v systému současně. Každý pracuje se svými záznamy. Pokud dva uživatelé editují stejnou fakturu, uloží se poslední změna. Doporučujeme koordinaci mezi uživateli.', 'Yes, multiple users can work in the system simultaneously. Each works with their records. If two users edit the same invoice, the last save wins. We recommend coordination between users.', '/invoices', 'feature', 5],

  // ═══════════════════════════════════════
  // NOTIFICATIONS & REMINDERS
  // ═══════════════════════════════════════
  ['notifikace,notification,upozornění,oznámení,zvonec,bell', 'Kde najdu notifikace?', 'Where are notifications?', 'Notifikace (oznámení) najdete kliknutím na ikonu zvonečku v horní liště. Systém vás upozorní na faktury po splatnosti, nové platby a důležité události.', 'Notifications are accessible by clicking the bell icon in the top bar. The system alerts you about overdue invoices, new payments and important events.', null, 'feature', 7],
  ['automatické upozornění,auto notification,email notification', 'Dostanu automatická upozornění?', 'Do I get automatic notifications?', 'Systém automaticky sleduje splatnost faktur. Když faktura přejde do stavu "Po splatnosti", zobrazí se upozornění. Můžete také odesílat upomínky klientům emailem.', 'The system automatically monitors invoice due dates. When an invoice becomes overdue, a notification appears. You can also send payment reminders to clients by email.', '/invoices', 'feature', 6],

  // ═══════════════════════════════════════
  // MULTI-CURRENCY ADVANCED
  // ═══════════════════════════════════════
  ['kurzový rozdíl,exchange difference,kurzová ztráta,kurzový zisk', 'Co je kurzový rozdíl?', 'What is an exchange rate difference?', 'Kurzový rozdíl vzniká při platbě faktury v cizí měně, když se kurz liší od kurzu při vystavení. Kladný rozdíl = kurzový zisk, záporný = kurzová ztráta. Zaúčtujte ho na účty 563 (ztráta) nebo 663 (zisk).', 'Exchange rate difference occurs when paying a foreign currency invoice at a different rate than when issued. Positive = exchange gain, negative = loss. Post to accounts 563 (loss) or 663 (gain).', '/accounting', 'terminology', 5],
  ['přepočet měn,currency conversion,konverze,převodník', 'Jak systém přepočítává měny?', 'How does the system convert currencies?', 'Systém používá denní kurzy ČNB, aktualizované každých 6 hodin. Při vytvoření faktury v cizí měně se automaticky vypočítá ekvivalent v CZK. Kurzy můžete zkontrolovat v Účetnictví → Měny.', 'The system uses daily CNB exchange rates, updated every 6 hours. When creating a foreign currency invoice, the CZK equivalent is auto-calculated. Check rates in Accounting → Currencies.', '/currencies', 'feature', 6],

  // ═══════════════════════════════════════
  // ADDITIONAL TROUBLESHOOTING
  // ═══════════════════════════════════════
  ['nelze smazat,cannot delete,nejde smazat,mazání nefunguje', 'Proč nemohu smazat fakturu?', 'Why can I not delete an invoice?', 'Smazat lze pouze faktury ve stavu Koncept nebo Stornovaná. Odeslanou nebo zaplacenou fakturu musíte nejprve stornovat (tlačítko "Stornovat"). Stornování zachová fakturu pro účetní účely.', 'Only Draft or Cancelled invoices can be deleted. Sent or paid invoices must be cancelled first ("Cancel" button). Cancellation preserves the invoice for accounting purposes.', '/invoices', 'help', 7],
  ['pdf nefunguje,pdf se nestáhne,generování pdf,pdf chyba', 'PDF se negeneruje', 'PDF is not working', 'Pokud se PDF negeneruje:\n1. Zkontrolujte, že faktura má všechny povinné údaje\n2. Ověřte nastavení společnosti (Správa → Společnost)\n3. Zkuste obnovit stránku\n4. Zkuste jiný prohlížeč\nPDF vyžaduje vyplněné údaje o společnosti (název, adresa).', 'If PDF is not generating:\n1. Check invoice has all required data\n2. Verify company settings (Admin → Company)\n3. Try refreshing the page\n4. Try a different browser\nPDF requires filled company info (name, address).', '/invoices', 'help', 6],
  ['špatný kurz,nesprávný kurz,kurz nesedí,wrong rate', 'Kurz na faktuře nesedí', 'Exchange rate is wrong', 'Kurzy se aktualizují z ČNB každých 6 hodin. Pokud kurz nesedí, zkuste v Účetnictví → Měny kliknout na "Obnovit kurzy". Kurz na existující faktuře se nemění — použije se kurz platný v době vystavení.', 'Rates update from CNB every 6 hours. If rate is wrong, try clicking "Refresh rates" in Accounting → Currencies. Rate on existing invoice does not change — it uses the rate valid at issue time.', '/currencies', 'help', 5],
  ['přihlášení nefunguje,login error,nelze přihlásit,špatné heslo', 'Nemohu se přihlásit', 'I cannot log in', 'Možné příčiny:\n• Špatné uživatelské jméno nebo heslo — zkontrolujte velká/malá písmena\n• Účet je deaktivován — kontaktujte administrátora\n• Příliš mnoho neúspěšných pokusů — počkejte 15 minut\n• Problém s prohlížečem — smažte cookies a zkuste znovu', 'Possible causes:\n• Wrong username or password — check caps lock\n• Account is deactivated — contact admin\n• Too many failed attempts — wait 15 minutes\n• Browser issue — clear cookies and try again', null, 'help', 7],
  ['pomalý systém,pomalé načítání,slow,výkon,performance', 'Systém je pomalý', 'System is slow', 'Zkuste:\n1. Obnovit stránku (F5)\n2. Vymazat cache prohlížeče\n3. Zkontrolovat rychlost internetu\n4. Použít méně otevřených záložek\n5. Zkusit jiný prohlížeč (Chrome, Firefox)\nPokud problém přetrvává, kontaktujte administrátora.', 'Try:\n1. Refresh page (F5)\n2. Clear browser cache\n3. Check internet speed\n4. Use fewer open tabs\n5. Try different browser (Chrome, Firefox)\nIf problem persists, contact admin.', null, 'help', 5],

  // ═══════════════════════════════════════
  // EET, GDPR & COMPLIANCE
  // ═══════════════════════════════════════
  ['eet,elektronická evidence tržeb,eet pokladna', 'Co je EET?', 'What is EET?', 'EET (Elektronická evidence tržeb) byla povinná evidence tržeb v ČR. Od 1.1.2023 byl EET zrušen zákonem. Systém EET nepodporuje, protože už není vyžadováno.', 'EET (Electronic Sales Registration) was a mandatory sales registration in CZ. Since 1.1.2023 EET was abolished by law. The system does not support EET as it is no longer required.', null, 'terminology', 5],
  ['gdpr,ochrana údajů,osobní údaje,data protection,privacy', 'Jak je řešeno GDPR?', 'How is GDPR handled?', 'Systém dodržuje GDPR — data jsou oddělena po tenantech, přístup je řízen rolemi, hesla jsou šifrována. Pro žádost o výmaz osobních údajů kontaktujte administrátora. Exportovat svá data můžete v sekci Společnost.', 'The system complies with GDPR — data is separated by tenant, access is role-based, passwords are encrypted. For data deletion requests contact admin. Export your data in Company section.', '/company', 'terminology', 6],
  ['živnostenský list,živnostník,osvč,self employed,podnikatel,freelancer,freelance', 'Mohu systém používat jako OSVČ?', 'Can I use the system as a freelancer?', 'Ano, systém je vhodný pro OSVČ i právnické osoby. Vyplňte své IČO, případně DIČ (pokud jste plátce DPH) v Správa → Společnost. Pro paušální daň stačí vést evidenci příjmů.', 'Yes, the system is suitable for freelancers and companies. Fill in your ID, optionally VAT ID in Admin → Company. For flat-rate tax, just record income in evidence.', '/company', 'feature', 6],

  // ═══════════════════════════════════════
  // COMMON USER QUESTIONS
  // ═══════════════════════════════════════
  ['jazyk,language,angličtina,čeština,přepnout jazyk', 'Mohu změnit jazyk?', 'Can I change the language?', 'Systém je primárně v češtině. Chatbot Hyňa rozumí česky i anglicky — pište v libovolném jazyce. Rozhraní systému je v češtině.', 'The system is primarily in Czech. Chatbot Hyňa understands both Czech and English — write in either language. The system interface is in Czech.', null, 'feature', 5],
  ['bezpečnost,security,šifrování,encryption,zabezpečení', 'Jak je systém zabezpečen?', 'How is the system secured?', 'Systém používá:\n• Šifrovaná hesla (bcrypt)\n• JWT autentizaci s expirací\n• Rate limiting proti brute-force útokům\n• Sanitizaci vstupů proti XSS\n• HTTPS hlavičky (HSTS, CSP)\n• Oddělení dat tenantů\n• Kontrolu oprávnění na každém endpointu', 'The system uses:\n• Encrypted passwords (bcrypt)\n• JWT authentication with expiration\n• Rate limiting against brute-force\n• Input sanitization against XSS\n• HTTPS headers (HSTS, CSP)\n• Tenant data isolation\n• Permission checks on every endpoint', null, 'feature', 6],
  ['přijaté faktury,received invoices,faktury od dodavatelů,došlé faktury', 'Kde eviduji přijaté faktury?', 'Where to record received invoices?', 'Přijaté faktury evidujte v sekci Evidence jako typ "Výdaj" nebo "Příjem". Případně je můžete zaznamenat jako přijatou fakturu v Faktury s typem "Přijatá". Pro DPH se přijaté faktury promítnou do vstupů.', 'Record received invoices in Evidence as "Expense" or use Invoices section with type "Received". For VAT, received invoices are reflected as inputs.', '/evidence', 'feature', 6],
  ['zálohová faktura,advance invoice,záloha na služby', 'Jak funguje zálohová faktura?', 'How does an advance invoice work?', 'Zálohovou fakturu vytvořte jako typ "Proforma". Po přijetí zálohy ji převeďte na řádnou fakturu. Pokud záloha pokrývá jen část, vystavte konečnou fakturu s odpočtem zálohy.', 'Create an advance invoice as type "Proforma". After receiving the advance, convert to a regular invoice. If the advance covers only part, issue a final invoice with advance deduction.', '/invoices/new', 'feature', 6],
  ['souhrnné hlášení,summary report,eu hlášení,intrastat', 'Co je souhrnné hlášení?', 'What is a summary report?', 'Souhrnné hlášení podávají plátci DPH za dodání zboží a služeb do jiných členských států EU. Podklady najdete v sekci DPH. Intrastat se podává při překročení limitu obchodování s EU.', 'Summary reports are filed by VAT payers for supplies to other EU member states. Data is in the VAT section. Intrastat is filed when exceeding EU trade thresholds.', '/vat', 'terminology', 5],
  ['slevy,sleva,discount,sleva na faktuře,rabat,přidat slevu,jak přidám slevu', 'Jak přidám slevu na fakturu?', 'How to add a discount to an invoice?', 'Slevu přidáte úpravou ceny položky nebo přidáním nové položky se zápornou částkou. Např. "Sleva 10%" s cenou -1000. Celková částka faktury se automaticky přepočítá.', 'Add a discount by adjusting the item price or adding a new item with negative amount. E.g. "10% discount" with price -1000. The invoice total is automatically recalculated.', '/invoices/new', 'feature', 8],
  ['poznámka,note,interní poznámka,fakturační poznámka', 'Jak přidám poznámku k faktuře?', 'How to add a note to an invoice?', 'Při vytváření nebo editaci faktury najdete pole "Poznámka" (zobrazí se na faktuře) a "Interní poznámka" (vidí jen uživatelé systému). Poznámky můžete využít pro platební podmínky nebo reference.', 'When creating or editing an invoice you find "Note" field (shown on invoice) and "Internal note" (visible only to system users). Use notes for payment terms or references.', '/invoices/new', 'feature', 5],
  ['přeplatek,overpayment,vrátit přeplatek,přeplatek na faktuře', 'Co dělat s přeplatkem?', 'What to do with an overpayment?', 'Pokud klient zaplatí více než je částka faktury, zaznamenejte plnou přijatou částku. Přeplatek můžete vrátit bankovním převodem a zaznamenat to v evidenci, nebo ho započítat proti další faktuře.', 'If a client pays more than the invoice amount, record the full received amount. Return the overpayment by bank transfer and record it in evidence, or offset it against the next invoice.', '/invoices', 'feature', 5],
  ['stornování,storno,stornovat fakturu,cancel invoice,zrušit fakturu,jak stornuji,jak zruším', 'Jak stornuji fakturu?', 'How to cancel an invoice?', 'V detailu faktury klikněte na "Stornovat". Stornovaná faktura zůstane v systému pro účetní účely, ale nepočítá se do přehledů. Pro opravu vystavte dobropis nebo novou fakturu.', 'In the invoice detail click "Cancel". Cancelled invoice remains in the system for accounting purposes but is excluded from reports. To correct, issue a credit note or new invoice.', '/invoices', 'feature', 8],
  ['notář,úředně ověřeno,apostila,legalizace', 'Potřebuji úředně ověřené faktury?', 'Do I need notarized invoices?', 'Ne, běžné faktury nevyžadují úřední ověření. Elektronická faktura (PDF) má stejnou právní váhu jako papírová. Pro zahraniční obchod může být vyžadována apostila — to řeší notář, nikoliv fakturační systém.', 'No, regular invoices do not require notarization. Electronic invoice (PDF) has the same legal validity as paper. For international trade an apostille may be required — handled by notary, not invoicing system.', null, 'terminology', 4],

  // ═══════════════════════════════════════
  // CHATBOT-SPECIFIC QUESTIONS
  // ═══════════════════════════════════════
  ['offline,bez internetu,funguje offline,internet', 'Funguje systém offline?', 'Does the system work offline?', 'Systém vyžaduje připojení k internetu. Data jsou uložena na serveru a přístup je přes webový prohlížeč. Bez internetu nelze systém používat. Doporučujeme pravidelné zálohy pro případ výpadku.', 'The system requires internet connection. Data is stored on the server and accessed via web browser. Without internet the system cannot be used. We recommend regular backups in case of outage.', null, 'feature', 5],
  ['prohlížeč,browser,chrome,firefox,safari,edge,kompatibilita', 'Jaké prohlížeče podporujete?', 'What browsers do you support?', 'Systém podporuje všechny moderní prohlížeče: Chrome, Firefox, Safari, Edge. Doporučujeme používat nejnovější verzi. Internet Explorer není podporován.', 'The system supports all modern browsers: Chrome, Firefox, Safari, Edge. We recommend using the latest version. Internet Explorer is not supported.', null, 'feature', 5],
  ['tisk,tisknout,print,vytisknout', 'Jak vytisknu fakturu?', 'How to print an invoice?', 'Stáhněte PDF faktury (tlačítko "Stáhnout PDF" v detailu) a vytiskněte z prohlížeče. Můžete také použít funkci prohlížeče Ctrl+P, ale PDF poskytuje lepší formátování s logem a QR kódem.', 'Download the invoice PDF ("Download PDF" button in detail) and print from browser. You can also use browser Ctrl+P, but PDF provides better formatting with logo and QR code.', '/invoices', 'feature', 6],
  ['srovnání,comparison,lepší než,alternativa,porovnání', 'Jak se tento systém srovnává s ostatními?', 'How does this system compare to others?', 'Náš ERP systém nabízí kompletní fakturaci, účetnictví, evidenci, bankovní propojení a AI chatbota — vše v jednom. Na rozdíl od jiných systémů máte plnou kontrolu nad daty a multi-tenant architekturu.', 'Our ERP system offers complete invoicing, accounting, evidence, banking integration and AI chatbot — all in one. Unlike other systems you have full data control and multi-tenant architecture.', null, 'help', 5],
  ['kolik stojí,cena,pricing,zdarma,poplatek,licence', 'Kolik systém stojí?', 'How much does the system cost?', 'Informace o ceníku a licencích získáte od administrátora vaší organizace nebo na kontaktní stránce. Systém je provozován jako SaaS (Software as a Service).', 'For pricing and licensing information contact your organization admin or visit the contact page. The system is operated as SaaS (Software as a Service).', null, 'help', 4],
  ['API,integrace,napojení,propojení,webhook,rest api', 'Má systém API pro integraci?', 'Does the system have an API?', 'Ano, systém poskytuje REST API pro integraci s dalšími aplikacemi. API vyžaduje autentizaci JWT tokenem. Dokumentaci API najdete u administrátora nebo v technické dokumentaci.', 'Yes, the system provides a REST API for integration with other applications. API requires JWT token authentication. API documentation is available from admin or technical docs.', null, 'feature', 5],
  ['mobilní aplikace,app,android,ios,appka', 'Existuje mobilní aplikace?', 'Is there a mobile app?', 'Dedikovaná mobilní aplikace zatím není k dispozici. Systém je ale plně responzivní — funguje v mobilním prohlížeči na Android i iOS stejně jako na počítači. Přidejte si záložku na plochu pro rychlý přístup.', 'A dedicated mobile app is not available yet. However, the system is fully responsive — it works in mobile browser on Android and iOS just like on desktop. Add a bookmark to home screen for quick access.', null, 'feature', 5],

  // ═══════════════════════════════════════
  // EDGE CASES & MISC
  // ═══════════════════════════════════════
  ['měsíční přehled,monthly overview,měsíční uzávěrka,konec měsíce', 'Jak udělám měsíční uzávěrku?', 'How to do a monthly close?', 'Na konci měsíce:\n1. Zkontrolujte, že všechny faktury jsou zaznamenány\n2. Spárujte bankovní transakce\n3. Zkontrolujte stav DPH v Účetnictví → DPH\n4. Případně uzavřete účetní období\n5. Vytvořte zálohu dat', 'At month end:\n1. Verify all invoices are recorded\n2. Match bank transactions\n3. Check VAT status in Accounting → VAT\n4. Optionally close the accounting period\n5. Create data backup', '/accounting', 'feature', 6],
  ['výpočet dph,kalkulace dph,dph kalkulačka,spočítat dph', 'Jak se počítá DPH?', 'How is VAT calculated?', 'DPH se počítá ze základu daně: základ × sazba. Např. 1000 Kč × 21% = 210 Kč DPH, celkem 1210 Kč. Při výpočtu ze shora (z částky včetně DPH): 1210 / 1.21 = 1000 Kč základ, DPH 210 Kč. Systém počítá automaticky.', 'VAT is calculated from tax base: base × rate. E.g. 1000 CZK × 21% = 210 CZK VAT, total 1210 CZK. Calculating from gross: 1210 / 1.21 = 1000 CZK base, VAT 210 CZK. System calculates automatically.', '/vat', 'terminology', 6],
  ['dobírka,cod,cash on delivery,platba při převzetí', 'Podporujete platbu na dobírku?', 'Do you support COD?', 'Ano, při vytváření faktury můžete zvolit způsob platby "Dobírka". Částka se zaznamenává jako obvykle — po přijetí platby od přepravce změňte stav na "Zaplacená".', 'Yes, when creating an invoice you can select payment method "Cash on delivery". Amount is recorded as usual — after receiving payment from the carrier, change status to "Paid".', '/invoices/new', 'feature', 5],
  ['srozumitelně,jednodušeji,nerozumím,vysvětli,explain,jednoduše', 'Nerozumím — vysvětli jednodušeji', 'I don\'t understand — explain simply', 'Zkuste se zeptat na konkrétní věc. Například:\n• "Jak udělám fakturu?" — krok za krokem\n• "Co znamená DPH?" — vysvětlím pojem\n• "Kde najdu klienty?" — naviguju vás\n• "Kolik mám faktur?" — zobrazím data\nJsem tu, abych pomohl!', 'Try asking about a specific thing. For example:\n• "How to create an invoice?" — step by step\n• "What does VAT mean?" — I explain the concept\n• "Where are clients?" — I navigate you\n• "How many invoices?" — I show data\nI am here to help!', null, 'help', 8],
  ['na shledanou,bye,sbohem,konec,goodbye,nashle', 'Rozloučení', 'Goodbye', 'Na shledanou! Kdykoliv budete potřebovat pomoct, jsem tu pro vás. Stačí otevřít chat!', 'Goodbye! Whenever you need help, I am here for you. Just open the chat!', null, 'help', 8],

  // ═══════════════════════════════════════
  // EXPANDED COVERAGE (from 1000+ test)
  // ═══════════════════════════════════════
  ['co je erp,erp systém,enterprise resource planning,erp meaning', 'Co je ERP systém?', 'What is an ERP system?', 'ERP (Enterprise Resource Planning) je systém pro řízení podnikových zdrojů. Integruje fakturaci, účetnictví, evidenci, bankovní operace, správu klientů a uživatelů do jednoho systému. Náš ERP vám pomáhá efektivně řídit celou firmu.', 'ERP (Enterprise Resource Planning) is a system for managing business resources. It integrates invoicing, accounting, evidence, banking, client and user management into one system.', '/', 'terminology', 6],
  ['saldo,zůstatek,balance,stav účtu', 'Co je saldo?', 'What is a balance?', 'Saldo je rozdíl mezi příjmy a výdaji, nebo zůstatek na účtu. V kontextu faktur je saldo rozdíl mezi fakturovanou částkou a přijatými platbami. Nulové saldo = plně uhrazeno.', 'Balance (saldo) is the difference between income and expenses, or account balance. In invoice context it is the difference between invoiced amount and received payments. Zero balance = fully paid.', '/accounting', 'terminology', 5],
  ['má dáti,dal,md,debet,kredit,strana účtu,md/d', 'Co je Má dáti a Dal?', 'What is Debit and Credit?', 'Má dáti (MD, Debit) a Dal (D, Credit) jsou dvě strany účetního zápisu. Každý zápis musí mít vyrovnanou stranu MD a D. Aktiva rostou na MD, klesají na D. Pasiva naopak. Náklady na MD, výnosy na D.', 'Debit (MD) and Credit (D) are two sides of a journal entry. Each entry must balance debit and credit. Assets increase on debit, decrease on credit. Liabilities are opposite.', '/accounting', 'terminology', 5],
  ['odpisy,depreciation,amortizace,odepisování', 'Co jsou odpisy?', 'What is depreciation?', 'Odpisy jsou postupné snižování hodnoty dlouhodobého majetku v účetnictví. Majetek se neúčtuje celý najednou, ale rozkládá se do více let. V ČR existují rovnoměrné a zrychlené odpisy. Zaúčtujte je v účetním deníku.', 'Depreciation is the gradual reduction of asset value in accounting. Assets are not expensed all at once but spread over years. In CZ there are straight-line and accelerated depreciation.', '/accounting', 'terminology', 5],
  ['podpora,support,technická podpora,kontakt podpora,helpdesk,help desk', 'Kde najdu technickou podporu?', 'Where is technical support?', 'Pro technickou podporu kontaktujte administrátora vaší organizace. Administrátor může řešit problémy s oprávněními, hesly a nastavením. Pro systémové problémy kontaktujte SuperAdmina.', 'For technical support contact your organization admin. Admin can resolve permission, password and settings issues. For system issues contact SuperAdmin.', '/company', 'help', 6],
  ['školení,training,kurz,výuka,naučit se,tutorial', 'Je k dispozici školení?', 'Is training available?', 'Systém je intuitivní a navržen pro snadné použití. Chatbot Hyňa vám pomůže s navigací a zodpoví otázky. Pro detailnější školení kontaktujte administrátora. Zkuste se ptát — pomohu vám krok za krokem!', 'The system is intuitive and designed for easy use. Chatbot Hyňa helps with navigation and answers questions. For detailed training contact admin. Try asking — I will help step by step!', null, 'help', 5],
  ['customer,zákazníci,odběratelé,buyers,customers', 'Kde spravuji zákazníky?', 'Where to manage customers?', 'Zákazníky (klienty) najdete v sekci Finance → Klienti. Zde můžete přidávat, upravovat a mazat zákazníky, vidět jejich faktury a kontaktní údaje.', 'Customers (clients) are in Finance → Clients. Here you can add, edit and delete customers, see their invoices and contact info.', '/clients', 'navigation', 7],
  ['přiřadit roli,změnit roli,role change,nastavit oprávnění', 'Jak změním roli uživatele?', 'How to change user role?', 'V Správa → Uživatelé klikněte na uživatele a změňte jeho roli (Admin, Účetní, Manažer, Náhled). Pouze administrátor může měnit role ostatním uživatelům.', 'In Admin → Users click on a user and change their role (Admin, Accountant, Manager, Viewer). Only admin can change other users roles.', '/users', 'feature', 6],
  ['odpočet dph,nárok na odpočet,input vat,vstupní dph', 'Co je odpočet DPH?', 'What is VAT deduction?', 'Odpočet DPH umožňuje plátcům odečíst DPH zaplacené na vstupu (přijaté faktury) od DPH na výstupu (vydané faktury). Nárok na odpočet máte pouze jako plátce DPH. Evidujte přijaté faktury s DPH v sekci Evidence.', 'VAT deduction allows payers to deduct input VAT (received invoices) from output VAT (issued invoices). Only VAT payers have this right. Record received invoices with VAT in Evidence.', '/vat', 'terminology', 6],
  ['responzivní,responsive design,přizpůsobení,adaptive', 'Je systém responzivní?', 'Is the system responsive?', 'Ano, systém je plně responzivní. Přizpůsobuje se velikosti obrazovky — funguje na počítači, tabletu i telefonu. Na mobilu se postranní panel skryje a otevřete ho přes ikonu menu.', 'Yes, the system is fully responsive. It adapts to screen size — works on desktop, tablet and phone. On mobile the sidebar hides and opens via menu icon.', null, 'feature', 5],
  ['timeout,časový limit,vypršení,session expired', 'Co znamená timeout?', 'What does timeout mean?', 'Timeout znamená, že vypršel časový limit přihlášení. Přihlaste se znovu. Pokud se timeout opakuje často, zkontrolujte připojení k internetu a zkuste obnovit stránku (F5).', 'Timeout means your login session has expired. Log in again. If timeout occurs frequently, check internet connection and try refreshing the page (F5).', null, 'help', 5],
];
knowledge.forEach(k => insertKnowledge.run(tenantId, ...k));

// ─── DEMO TENANT 2 (globally unique usernames!) ─────────────
const existingDemo = db.prepare("SELECT id FROM tenants WHERE slug = 'demo'").get();
let demoTenantId;
if (!existingDemo) {
  const demoInviteCode = crypto.randomBytes(6).toString('hex');
  const r = db.prepare("INSERT INTO tenants (name, slug, invite_code) VALUES ('Demo firma s.r.o.', 'demo', ?)").run(demoInviteCode);
  demoTenantId = r.lastInsertRowid;
  // Unique username: demo-admin (not 'admin' — that's taken by RFI tenant)
  db.prepare('INSERT INTO users (tenant_id, username, email, password, full_name, first_name, last_name, role) VALUES (?,?,?,?,?,?,?,?)')
    .run(demoTenantId, 'demo-admin', 'admin@demo.cz', hash('admin123'), 'Demo Admin', 'Demo', 'Admin', 'admin');
  db.prepare("INSERT INTO company (tenant_id, name, ico, dic, invoice_prefix, invoice_counter) VALUES (?, 'Demo firma s.r.o.', '99887766', 'CZ99887766', 'DF', 1)").run(demoTenantId);
}

// Print invite codes
const rfiTenant = db.prepare("SELECT invite_code FROM tenants WHERE slug = 'rfi'").get();
const demoTenant = db.prepare("SELECT invite_code FROM tenants WHERE slug = 'demo'").get();

console.log('Database seeded successfully!');
console.log('Superadmin: superadmin / super123');
console.log('Tenant "rfi": admin/admin123, ucetni/ucetni123, manager/manager123, viewer/viewer123');
console.log(`  Invite code: ${rfiTenant?.invite_code || 'N/A'}`);
console.log('Tenant "demo": demo-admin/admin123');
console.log(`  Invite code: ${demoTenant?.invite_code || 'N/A'}`);
